openapi: 3.0.3
info:
  title: US Census Bureau API
  description: Community-defined OpenAPI 3.0 schema for the US Census API (dynamic dataset paths, query params)
  version: "1.0.0"
  contact:
    name: US Census Developer
    url: https://www.census.gov/data/developers/data-sets.html
    email: census.api.support@census.gov

servers:
  - url: https://api.census.gov

paths:
  /data/{year}/{dataset}:
    get:
      summary: Get Census Data from a specific dataset and year
      parameters:
        - name: year
          in: path
          required: true
          schema:
            type: string
        - name: dataset
          in: path
          required: true
          schema:
            type: string
            example: acs/acs5
        - name: get
          in: query
          required: true
          schema:
            type: string
            example: NAME,B01001_001E
        - name: for
          in: query
          required: true
          schema:
            type: string
            example: county:* 
        - name: in
          in: query
          required: false
          schema:
            type: string
            example: state:06
        - name: key
          in: query
          required: false
          schema:
            type: string
            example: YOUR_CENSUS_API_KEY
      responses:
        "200":
          description: Successful response
          content:
            application/json:
              schema:
                type: array
                items:
                  type: array
                  items:
                    type: string

  /data/{year}/{dataset}/variables.json:
    get:
      summary: Get list of available variables
      parameters:
        - name: year
          in: path
          required: true
          schema:
            type: string
        - name: dataset
          in: path
          required: true
          schema:
            type: string
            example: acs/acs5
      responses:
        "200":
          description: List of variables
          content:
            application/json:
              schema:
                type: object
                additionalProperties:
                  type: object
                  properties:
                    label:
                      type: string
                    concept:
                      type: string
                    predicateType:
                      type: string
                    group:
                      type: string

  /data/{year}/{dataset}/geography.json:
    get:
      summary: Get list of available geographies
      parameters:
        - name: year
          in: path
          required: true
          schema:
            type: string
        - name: dataset
          in: path
          required: true
          schema:
            type: string
            example: acs/acs5
      responses:
        "200":
          description: Geography metadata
          content:
            application/json:
              schema:
                type: object

  /data/{year}/{dataset}/examples.json:
    get:
      summary: Get example queries for a dataset
      parameters:
        - name: year
          in: path
          required: true
          schema:
            type: string
        - name: dataset
          in: path
          required: true
          schema:
            type: string
            example: acs/acs5
      responses:
        "200":
          description: Example API usage
          content:
            application/json:
              schema:
                type: object
                additionalProperties:
                  type: object
